/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewProductenRouteImport } from './routes/preview.producten'
import { Route as PreviewDeflectionCardRouteImport } from './routes/preview.deflection-card'
import { Route as PreviewDecoderCardRouteImport } from './routes/preview.decoder-card'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewProductenRoute = PreviewProductenRouteImport.update({
  id: '/preview/producten',
  path: '/preview/producten',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewDeflectionCardRoute = PreviewDeflectionCardRouteImport.update({
  id: '/preview/deflection-card',
  path: '/preview/deflection-card',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewDecoderCardRoute = PreviewDecoderCardRouteImport.update({
  id: '/preview/decoder-card',
  path: '/preview/decoder-card',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preview/decoder-card': typeof PreviewDecoderCardRoute
  '/preview/deflection-card': typeof PreviewDeflectionCardRoute
  '/preview/producten': typeof PreviewProductenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preview/decoder-card': typeof PreviewDecoderCardRoute
  '/preview/deflection-card': typeof PreviewDeflectionCardRoute
  '/preview/producten': typeof PreviewProductenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preview/decoder-card': typeof PreviewDecoderCardRoute
  '/preview/deflection-card': typeof PreviewDeflectionCardRoute
  '/preview/producten': typeof PreviewProductenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/preview/decoder-card'
    | '/preview/deflection-card'
    | '/preview/producten'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/preview/decoder-card'
    | '/preview/deflection-card'
    | '/preview/producten'
  id:
    | '__root__'
    | '/'
    | '/preview/decoder-card'
    | '/preview/deflection-card'
    | '/preview/producten'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreviewDecoderCardRoute: typeof PreviewDecoderCardRoute
  PreviewDeflectionCardRoute: typeof PreviewDeflectionCardRoute
  PreviewProductenRoute: typeof PreviewProductenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/producten': {
      id: '/preview/producten'
      path: '/preview/producten'
      fullPath: '/preview/producten'
      preLoaderRoute: typeof PreviewProductenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/deflection-card': {
      id: '/preview/deflection-card'
      path: '/preview/deflection-card'
      fullPath: '/preview/deflection-card'
      preLoaderRoute: typeof PreviewDeflectionCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/decoder-card': {
      id: '/preview/decoder-card'
      path: '/preview/decoder-card'
      fullPath: '/preview/decoder-card'
      preLoaderRoute: typeof PreviewDecoderCardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviewDecoderCardRoute: PreviewDecoderCardRoute,
  PreviewDeflectionCardRoute: PreviewDeflectionCardRoute,
  PreviewProductenRoute: PreviewProductenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
